### ISSUE TITLE
Allow using both rusqlite and libsql in the same process

### ISSUE THREAD

**Issue by wyhaya** [tursodatabase/libsql#526] opened 2023-10-28 23:05 UTC
```toml
[dependencies]
libsql = { git = "https://github.com/tursodatabase/libsql" }
rusqlite = { version = "0.29" }
```

### Run

```rust
fn test() {
    rusqlite::Connection::open_in_memory().unwrap();
    libsql::Database::open_in_memory().unwrap().connect().unwrap();
}
```
### Output
```
thread 'main' panicked at /Users/.../libsql-311658d335deb3b1/c9b60a1/libsql/src/local/database.rs:88:17:
assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
                the api is not safe to use. Please check that no multi-thread options have
                been set. If nothing was configured then please open an issue at:
                https://github.com/libsql/libsql
  left: 21
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/tursodatabase/libsql/blob/c9b60a1c8ed47889f39e25b5d105130245cc1403/libsql/src/local/database.rs#L84-L103

**Comment by wyhaya** [comment] 2023-10-28 23:05
It's worth noting that if you open `libSQL` once before opening `SQLite`, then this error will not occur.

```rust
// No error
fn test() {
    libsql::Database::open_in_memory().unwrap().connect().unwrap();
    rusqlite::Connection::open_in_memory().unwrap();
    libsql::Database::open_in_memory().unwrap().connect().unwrap();
}
```
I'm not sure if this is safe, but it seems like a temporary solution if one wants to use `libSQL` and `SQLite` at the same time?

**Comment by MarinPostma** [comment] 2023-10-29 08:55
This is somewhat expected, but we must find a better way @LucioFranco. @wyhaya The issue is that sqlite uses globals for initialization. libsql expects sqlite te be setup a certain way, but if you initialize sqlite first, then libsql is unable to initialize itself properly. Initializing libsql first is the workaround for now.

**Comment by LucioFranco** [comment] 2023-10-30 15:03
@wyhaya yeah, your workaround is the correct way to do this at the moment. This is due to the nature of sqlite config being per process. We eventually will likely in the future not use the different config and will not have this issue but until then the workaround that you found is exactly correct! Its totally safe, this is because libsql sets serialized mode which rusqlite's implementation uses multi-thread which is a subset of the serialized code. Basically, if we used the rusqlite's config item our code would be unsafe but if we use the libsql one then both rusqlite/libsql are safe.

**Comment by wyhaya** [comment] 2023-11-18 04:07
The libsql `extension` does not work when using libsql and rusqlite together

```rs
#[tokio::main]
async fn main() {
    // First init libsql
    let _ = libsql::Database::open_in_memory()
        .unwrap()
        .connect()
        .unwrap();

    let sqlite = rusqlite::Connection::open_in_memory().unwrap();
    let libsql = libsql::Database::open_in_memory()
        .unwrap()
        .connect()
        .unwrap();

    // If this line is deleted, there is no error
    sqlite.query_row("SELECT 1", (), |_| Ok(())).unwrap();

    libsql
        .execute(
            "CREATE TABLE shopping_list(item text, quantity int) RANDOM ROWID;",
            (),
        )
        .await
        .unwrap();
}
```
### Error
```
thread 'main' panicked at src/main.rs:24:10:
called `Result::unwrap()` on an `Err` value: SqliteFailure(1, "near \"ROWID\": syntax error")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MarinPostma** [comment] 2023-11-18 20:00
@psarna any idea on what could be going on here?

**Comment by psarna** [comment] 2023-11-19 14:01
The syntax error suggests that SQLite library (from rusqlite I guess) was linked, and SQLite does not support `RANDOM ROWID` syntax. For using rusqlite that uses libsql library, it should be added as git dependency to our fork: `rusqlite = { git = "https://github.com/tursodatabase/rusqlite"}`, with the same features we use in sqld: https://github.com/tursodatabase/libsql/blob/5ca530e7871af0b8e8290e74e32fadfaba352463/Cargo.toml#L28-L32

**Comment by MarinPostma** [comment] 2023-11-19 18:55
@psarna I don't think that's the issue here, the query is executed against the libsql connection.

Besides, that fork is not really maintained since we don't use it anymore, so we probably need to make a decision about it's future

**Comment by psarna** [comment] 2023-11-19 19:04
> @psarna I don't think that's the issue here, the query is executed against the libsql connection.

Yes, but this code is compiled into a binary, and both libsqlite3 (provided by rusqlite) and liblibsql (provided by `libsql`) have the same symbol names for handling local databases. Only one of them can provide the symbols, so looks like the ones from rusqlite were linked

**Comment by MarinPostma** [comment] 2023-11-19 20:10
is there a way we could prevent rusqlite to link to its version of sqlite, and let us link ours instead? Since they share the same symbols, they should be compatible no? The issue is that rustqlite links theirs before us, correct?

**Comment by MarinPostma** [comment] 2023-11-19 20:14
Behold a dirty, untested trick. According to that: https://github.com/rusqlite/rusqlite/blob/master/libsqlite3-sys/build.rs#L42-L47, the `in_gecko` feature prevents linking in rusqlite, so _maybe_ activating this feature would let libsql link to its version of sqlite instead?

**Comment by wyhaya** [comment] 2023-11-20 12:29
use `in_gecko ` feature :

```rust
#[tokio::main]
async fn main() {
    let _ = libsql::Database::open_in_memory().unwrap().connect() .unwrap();

    let sqlite = rusqlite::Connection::open_in_memory().unwrap();
    // !!! It should fail, but it run successfully
    sqlite
        .execute(
            "CREATE TABLE shopping_list(item text) RANDOM ROWID;",
            (),
        )
        .unwrap();
}
```

**Comment by MarinPostma** [comment] 2023-11-20 20:49
Running it as a child process will not work either, because SQLite is linked statically... maybe by linking SQLite dynamically and libsql statically, wdyt @sarna?

**Comment by wyhaya** [comment] 2023-11-22 12:39
@MarinPostma Thanks. I built rusqlite as a `dylib` and now libsql / rusqlite works perfectly at the same time.

**Comment by MarinPostma** [comment] 2023-11-22 17:06
closing then :)

**Closed by MarinPostma** 2023-11-22 17:06 UTC
